ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8888
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
